version: '3'
services:
  gateway:
    restart: unless-stopped
    build:
      context: ./gateway
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - auth
  auth:
    build:
      context: ./auth
      target: development
    volumes:
      - ./auth:/app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/postgres?schema=public
      - REDIS_URL=redis://redis:6379
    networks:
      - my-network
    depends_on:
      - redis
      - rabbitmq
      - postgres
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network

  products:
    build:
      context: ./products
      target: development
    volumes:
      - ./products:/app
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/products?schema=public
    networks:
      - my-network
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my-network

  rabbitmq:
    image: "rabbitmq:3.12-management-alpine"
    container_name: rabbitmq-container
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

networks:
  my-network:
