# Use the official Nginx image as the base image
FROM nginx

# Copy the Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 (the port Nginx will listen on)
EXPOSE 80